[platformio]
src_dir = esp32_marauder
test_dir = test

[env:native]
platform = native@1.2.1
test_framework = unity
test_build_src = true
extra_scripts =
  pre:tools/native_coverage.py
build_src_filter =
  -<*>
  +<MarauderMacAddress.cpp>
  +<PcapHeader.cpp>
  +<Switches.cpp>
build_flags =
  -std=gnu++17
  -Wall
  -Wextra
  -Wpedantic
  --coverage
  -Itest/support
