# bundle exec jekyll serve --host=0.0.0.0

title: ESP Async WebServer
description: "Asynchronous HTTP and WebSocket Server Library for ESP32"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  